"""Regenerate the frontend's offline copy of the variable schemas.

Run from the repo root with `uv run python scripts/generate_bundled_schemas.py`.
The output is committed so the editor still renders when the API is unreachable.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.models.input_models._general import (  # noqa: E402
    _get_cached_service_config_models,
)

OUTPUT = Path(__file__).resolve().parents[1] / "frontend/src/data/bundled-schemas.ts"

HEADER = """/**
 * Bundled copy of variable schemas — fallback when /api/variable-schemas is unreachable.
 *
 * Generated by scripts/generate_bundled_schemas.py. Do not edit by hand.
 */

import type { ServiceVariableSchemas } from '@/types/terraform-variables';

export const BUNDLED_SCHEMAS: ServiceVariableSchemas = """


def build_schemas() -> dict[str, list[dict]]:
    """Introspect every service config model into serialisable schema entries."""
    return {
        service_type.value: [
            entry.model_dump(exclude_none=True)
            for entry in config_cls.get_variable_schema()
        ]
        for service_type, config_cls in _get_cached_service_config_models().items()
        if config_cls.has_terraform_schema()
    }


def main() -> None:
    body = json.dumps(build_schemas(), indent=2, sort_keys=True)
    OUTPUT.write_text(HEADER + body + ";\n")
    subprocess.run(
        ["corepack", "pnpm", "exec", "prettier", "--write", str(OUTPUT)],
        cwd=OUTPUT.parents[3],
        capture_output=True,
    )
    print(f"wrote {OUTPUT.relative_to(Path.cwd())}")


if __name__ == "__main__":
    main()
